# Generated by Django 4.0 on 2022-01-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frst_app', '0002_orders_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orders',
            new_name='order',
        ),
    ]
